name: Build and Test RESTful Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11' # Adjust the Java version as needed
    
    - name: Build the container image
      run: docker build . -t my-restful-service
      
    - name: Run the container
      run: docker run -d -p 8123:8123 my-restful-service
      
    - name: Wait for the container to start up
      run: sleep 5
      
    - name: Test the RESTful service
      run: |
        # Send a GET request to the service
        response=$(curl localhost:8123/fib?length=18)
        
        # Check the response
        if [ "$response" == "<expected_response>" ]; then
          echo "Test passed!"
        else
          echo "Test failed. Expected '<expected_response>', got '$response'"
          exit 1
        fi
